version: 1.0
app:
  instances:
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: "CHANGE_ME"
    - name: clientId
      value: "CHANGE_ME"
  version: "7ceccba1-3941-4aaa-ac6d-21f2e19c1346"
  java: 17
