version: 1.0
app:
  instances:
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: "CHANGE_ME"
    - name: clientId
      value: "CHANGE_ME"
  version: "1181ec95-bf62-4cd5-a99d-2162f7cfac16"
  java: 17
